### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by SpaceMonkeyForever** [coinbase/gdax-tt#114]
Is it possible to use this library on client-side (browser)?

**Comment by Ameobea** [comment]
Right now, the library depends on the `ws` module which is node-only.  However, I'm pretty sure that its websocket implementation is identical to the browser's `WebSocket`, and so it should be possible to just use that instead.

Other than that, there may be some issues with making web requests.  It doesn't look like this library reies on any fetch polyfills, but there may need to be some changes made to accommodate the different environment.

Other than those things, which are both things that can be handled, I don't see anything that should prevent this library being used in a web browser with some changes.  I feel like there's some way to run the test suite in a browser environment, but I'm not sure how to do it.

**Comment by CjS77** [comment]
There's no plan for client-side support. You could fork the project to try and make it work, but I struggle to see the value, since the GTT is very much a  backend focused project. 

If your goal is communicating with a UI, then the server folder has an embryonic WS server implementation that you could maybe use as a platform for sending messages to a front-end; or you could look at building on the POC project [rpc-crypto](https://github.com/CjS77/rpc-crypto)
