### ISSUE TITLE
Create the gtt-ui project

### ISSUE THREAD

**Issue by balupton** [coinbase/gdax-tt#52]
It is currently referenced by the documentation, but it does not exist anywhere. Creating this issue as a reference to its status that the documentation can link to.

**Comment by CjS77** [comment]
Done. https://github.com/coinbase/gtt-ui
I'll add some POC code soon

**Comment by balupton** [comment]
I'm getting 404 - is it still a private repo?

**Comment by kroitor** [comment]
Yeah, me too: 404...

**Comment by CjS77** [comment]
It might still be, but that is the correct link.

**Comment by krem06** [comment]
Guys the project looks awesome ! Keep up the good work ;) Looking forward to version 1.0

**Comment by kroitor** [comment]
@CjS77 the link might be correct, but it still says 404 to me, so, maybe there's some permission setting left over that does not allow me (and probably others) to open that link? I tried refreshing, and also tried in several browsers with the same result.

**Comment by CjS77** [comment]
It's public now. Please take note that the demo project is currently broken there and it's unlikely to be fixed until we're at least on Beta here and the unified API is settling down.

**Comment by rongierlach** [comment]
how committed are coinbase to the gdax-tt & gtt-ui projects?

have been super excited for these projects since announcment but not a lot of movement forward it seems.

would love to combine forces and help out on the UI side of things, I already have a very much on-brand ui library started: https://github.com/rongierlach/react-trading-ui
